<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../'))" />
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="11.0.0-rc.1.26425.128" />
    <PackageVersion Include="Microsoft.Extensions.ApiDescription.Server" Version="11.0.0-rc.1.26425.128" />
    <PackageVersion Include="Microsoft.OpenApi" Version="3.10.2" />
    <PackageVersion Include="OpenTelemetry" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.Console" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerUi" Version="10.2.3" />
  </ItemGroup>
</Project>